package dev.ancaghenade.shipmentlistdemo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.lang.NonNull;

@Data
@Getter
@Setter
@Builder
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "shipment")
public class Shipment {


  @DynamoDBHashKey
  @DynamoDBAutoGeneratedKey
  private String shipmentId;

  @DynamoDBAttribute
  @NonNull
  private Participant recipient;

  @DynamoDBAttribute
  @NonNull
  private Participant sender;

  @DynamoDBAttribute
  private Double weight;

  @DynamoDBAttribute
  private String imageLink;

}